### ISSUE TITLE
Not able to open checker 

### ISSUE THREAD

**Issue by DevendarReddyDarukumalli** [call-042PE/Mephistopheles#2]
Getting  this error 

 Problem Event Name:	CLR20r3
  Problem Signature 01:	Luxify.exe
  Problem Signature 02:	1.1.0.0
  Problem Signature 03:	5e9a1093
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3451.0
  Problem Signature 06:	5d37b695
  Problem Signature 07:	20b3
  Problem Signature 08:	78
  Problem Signature 09:	System.Net.WebException
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	3e10
  Additional Information 2:	3e1092896f545064d974d466a8b7824f
  Additional Information 3:	0344
  Additional Information 4:	0344f182d62b29218d28ff7a854d3858

**Comment by call-042PE** [comment]
Did you install the server.crt to trusted root certification authorities ?

**Comment by DevendarReddyDarukumalli** [comment]
Yes I have installed the crt to trusted root certification authorities.

**Comment by DevendarReddyDarukumalli** [comment]
Will it work on windows 8 2012 ??

**Comment by call-042PE** [comment]
You have to install python3 and make sure you add it to the path
