### ISSUE TITLE
Cant access cracked after crt

### ISSUE THREAD

**Issue by JohnNielse** [call-042PE/Mephistopheles#4]
getting "This site can’t be reached, cracked.to refused to connect."
after adding the crt

**Comment by call-042PE** [comment]
https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/ and remove "`127.0.0.1 cracked.to"`

**Comment by JohnNielse** [comment]
Thanks, Possible to make it automatically edit it back when stopping the service?

**Comment by call-042PE** [comment]
Yeah just click stop

**Comment by JohnNielse** [comment]
lol yeh sorry
